"""Safe local .env writer for self-hosted ChoBot installs."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
import os
from pathlib import Path
import re
import shutil


PROJECT_ROOT = Path(__file__).resolve().parents[1]
LOCAL_ENV_PATH = PROJECT_ROOT / ".env.local"
SECRET_KEYS = {"DISCORD_TOKEN", "TWITCH_TOKEN", "DASHBOARD_SECRET", "FLASK_SECRET_KEY", "DISCORD_CLIENT_SECRET"}

SETUP_FIELDS = [
    "DASHBOARD_SECRET",
    "DISCORD_TOKEN",
    "GUILD_ID",
    "SUB_CATEGORY_ID",
    "FREE_CATEGORY_ID",
    "ORDERBOT_CHANNEL_IDS",
    "ORDERBOT_AUTHOR_IDS",
    "FLIGHT_LISTEN_CHANNEL_ID",
    "FREE_ISLAND_FLIGHT_LISTEN_CHANNEL_ID",
    "FLIGHT_LOG_CHANNEL_ID",
    "FREE_DODO_BOARD_CHANNEL_ID",
    "ISLAND_ACCESS_ROLE",
    "ADMIN_ROLE_ID",
    "TWITCH_TOKEN",
    "TWITCH_CHANNEL",
    "DODO_STALE_MINUTES",
]

_ID_LIST_KEYS = {"ORDERBOT_CHANNEL_IDS", "ORDERBOT_AUTHOR_IDS"}
_INT_KEYS = {
    "GUILD_ID",
    "SUB_CATEGORY_ID",
    "FREE_CATEGORY_ID",
    "FLIGHT_LISTEN_CHANNEL_ID",
    "FREE_ISLAND_FLIGHT_LISTEN_CHANNEL_ID",
    "FLIGHT_LOG_CHANNEL_ID",
    "FREE_DODO_BOARD_CHANNEL_ID",
    "ISLAND_ACCESS_ROLE",
    "ADMIN_ROLE_ID",
    "DODO_STALE_MINUTES",
}


@dataclass(frozen=True)
class LocalConfigWriteResult:
    path: str
    backup_path: str | None
    values: dict[str, str]


def read_local_setup_config(mask_secrets: bool = True) -> dict[str, str]:
    values = {key: os.getenv(key, "") or "" for key in SETUP_FIELDS}
    values.update(_parse_env_file(LOCAL_ENV_PATH))
    if mask_secrets:
        return {key: _mask_secret(value) if key in SECRET_KEYS else value for key, value in values.items()}
    return values


def write_local_setup_config(values: dict[str, object]) -> LocalConfigWriteResult:
    sanitized = _sanitize_setup_values(values)
    existing = _parse_env_file(LOCAL_ENV_PATH)
    merged = {**existing, **sanitized}

    backup_path = None
    if LOCAL_ENV_PATH.exists():
        stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
        backup = LOCAL_ENV_PATH.with_name(f".env.local.{stamp}.bak")
        shutil.copy2(LOCAL_ENV_PATH, backup)
        backup_path = str(backup)

    _write_env_file(LOCAL_ENV_PATH, merged)
    return LocalConfigWriteResult(path=str(LOCAL_ENV_PATH), backup_path=backup_path, values=sanitized)


def _sanitize_setup_values(values: dict[str, object]) -> dict[str, str]:
    sanitized: dict[str, str] = {}
    for key in SETUP_FIELDS:
        raw = str(values.get(key, "") or "").strip()
        if not raw:
            continue
        if key in SECRET_KEYS and _looks_masked_secret(raw):
            continue
        if key in _ID_LIST_KEYS:
            parts = [part.strip() for part in raw.replace("\n", ",").split(",") if part.strip()]
            if not all(part.isdigit() for part in parts):
                raise ValueError(f"{key} must be a comma-separated list of numeric Discord IDs")
            sanitized[key] = ",".join(parts)
        elif key in _INT_KEYS:
            if not raw.isdigit():
                raise ValueError(f"{key} must be a numeric value")
            sanitized[key] = raw
        else:
            sanitized[key] = raw
    return sanitized


def _looks_masked_secret(value: str) -> bool:
    return value == "********" or bool(re.fullmatch(r".{1,8}\.\.\..{1,8}", value))


def _parse_env_file(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    values: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.strip() or line.lstrip().startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", key):
            continue
        values[key] = _unquote(value.strip())
    return values


def _write_env_file(path: Path, values: dict[str, str]) -> None:
    ordered = []
    seen = set()
    for key in SETUP_FIELDS:
        if key in values:
            ordered.append((key, values[key]))
            seen.add(key)
    for key in sorted(k for k in values if k not in seen):
        ordered.append((key, values[key]))

    lines = [
        "# ChoBot local self-hosted configuration",
        "# This file is generated by /dashboard/setup/wizard and overrides .env.",
    ]
    lines.extend(f"{key}={_quote(value)}" for key, value in ordered)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _quote(value: str) -> str:
    if not value:
        return ""
    if re.search(r"\s|#|=|\"|'|\\", value):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    return value


def _unquote(value: str) -> str:
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {'"', "'"}:
        value = value[1:-1]
    return value.replace('\\"', '"').replace("\\\\", "\\")


def _mask_secret(value: str) -> str:
    if not value:
        return ""
    if len(value) <= 8:
        return "********"
    return f"{value[:4]}...{value[-4:]}"
